services:
  - type: web
    name: mortality-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -chdir src app:server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3